item { 
	name:'ThumbsUp'
	id:1
}
item { 
	name:'ThumbsDown'
	id:2
}
item { 
	name:'ThankYou'
	id:3
}
item { 
	name:'LiveLong'
	id:4
}
item { 
	name:'Welcome'
	id:5
}
item { 
	name:'Yes'
	id:6
}
item { 
	name:'Hello'
	id:7
}
item { 
	name:'No'
	id:8
}
